version: '2'
services:
  php:
    image: torphp
    volumes:
      - ./firefox-profiles:/root/.mozilla/firefox
      - ./google-jsons:/google-jsons:ro

  selenium:
    image: selenium/standalone-firefox-debug:3.4.0-chromium
    ports:
      - "5900:5900"
